apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-frontend
  template:
    metadata:
      labels:
        app: canary-frontend
    spec:
      containers:
        - name: frontend
          image: mrigankwastaken/canary-resilience-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "http://canary-backend:3000"
